train:
  _target_: src.datasets.LJSpeechDataset
  part: train
  chunk_size: 8192
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LJSpeechDataset
  part: val
  chunk_size: 8192
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
