_target_: src.model.HiFiGAN
generator_in_channels: 80
h_u: 512
k_u:
  - 16
  - 16
  - 4
  - 4
k_r:
  - 3
  - 7
  - 11
D_r:
  - [1, 1]
  - [3, 1]
  - [5, 1]
periods:
  - 2
  - 3
  - 5
  - 7
  - 11
msd_n_blocks: 3
generator_norm_type: weight
mpd_norm_type: weight
msd_use_norm: true
negative_slope: 0.1
expand_kernel_size: 7
project_kernel_size: 7
