train:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
    config:
      _target_: src.transforms.mel_spectrogram.MelSpectrogramConfig
inference:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
    config:
      _target_: src.transforms.mel_spectrogram.MelSpectrogramConfig
