_target_: src.logger.WandBWriter
project_name: "pytorch_template"
entity: null
run_name: "hifigan"
mode: "online"
loss_names: ["d_loss", "d_loss_mpd", "d_loss_msd", "g_loss", "g_adv_loss", "g_feature_loss", "g_mel_loss"]
log_checkpoints: False
id_length: 8
